name: mightyvpn
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.4
  device_info_plus: ^3.2.3
  firebase_analytics: ^9.1.5
  firebase_core: ^1.14.1
  firebase_crashlytics: ^2.6.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.4
  flutter_svg: ^1.0.3
  flutter_vector_icons: ^1.0.0
  get_ip_address: ^0.0.5
  google_fonts: ^2.3.1
  google_mobile_ads: ^1.2.0
  http: ^0.13.4
  image_picker: ^0.8.5
  in_app_review: ^2.0.4
  internet_speed_test: ^1.5.0
  mobx: ^2.0.6+1
  nb_utils: ^4.4.17
  package_info: ^2.0.2
  percent_indicator: ^4.0.0
  rflutter_alert: ^2.0.4
  share_plus: ^4.0.2
  syncfusion_flutter_gauges: ^20.1.48
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.10
  #flutter packages pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/opvn/
    - assets/flag/
